baseurl = "http://chuanyi.github.io/"
title = "传义"
canonifyurls = true
[params]
  author = "Zheng Chuanyi"
  description = "IT人，乐活主义"
[[menu.main]]
    name = "技术"
    url = "/tech"
    weight = 1
[[menu.main]]
    name = "产品"
    url = "/product"
    weight = 2
[[menu.main]]
    name = "创业"
    url = "/starter"
    weight = 3
[[menu.main]]
    name = "阅读"
    url = "/read"
    weight = 4
[[menu.main]]
    name = "关于"
    url = "/about"
    weight = 5                